# Helloworld application- just the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-deployment
spec:
  selector:
    matchLabels:
      app: flask_web
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: flask_web
    spec:
      containers:
      - name: flask-web-container
        image: ibrahim12/flask-web:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask_web

