apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
spec:
  selector:
    matchLabels:
      app: urlshortener
  replicas: 1 
  template: 
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - name: urlshortener-container
        image: la22/urlshortener:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: urlshortener-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: urlshortener
